### ISSUE TITLE
SVCB record support

### ISSUE THREAD

**Issue by bt90** [timothymiller/cloudflare-ddns#107]
HTTP/3 has been finalized as a standard and we're going to see adoption rising in the coming months. The SVCB DNS record allows clients to directly connect via HTTP/3 without a prior HTTP 1/2 connection.

https://blog.cloudflare.com/speeding-up-https-and-http-3-negotiation-with-dns/

It would be nice if the DDNS client could keep the IPv4/IPv6 hints updated:

```
example.com 3600 IN HTTPS 1 . alpn=”h3,h2” ipv4hint=”192.0.2.1” ipv6hint=”2001:db8::1”
```

**Comment by favonia** [comment]
The latest standard draft discourages unnecessary `ipv4hint` and `ipv6hint`, especially in this case. See https://www.ietf.org/archive/id/draft-ietf-dnsop-svcb-https-10.html#section-7.4-5:
> [....] When TargetName is the origin hostname or the owner name (which can be written as "."), server operators SHOULD NOT include these hints, because they are unlikely to convey any performance benefit.

The reason is that authoritative `A` and/or `AAAA` records of `example.com` will be immediately available, and the client SHOULD (in the IETF sense) ignore these hints when it learns the actual `A` and/or `AAAA` records. They are just hints.

_PS: I can't mention other programs or my message could be deleted. :slightly_smiling_face:_
