### ISSUE TITLE
IPv4 not detected

### ISSUE THREAD

**Issue by hegocre** [timothymiller/cloudflare-ddns#111]
**Describe the bug**
After the commit https://github.com/timothymiller/cloudflare-ddns/commit/ceeb0113667070301ae686c057f9173cfc94e053, cloudflare-ddns cannot detect the IPv4 IP. Reverting the commit fixes the problem.

**To Reproduce**
1. Copy the docker compose from README.md
2. Copy config.json, and adapt to the cloudflare account
3. Start the container'
4. See error "IPv4 not detected"

**Expected behavior**
The IPv4 IP is detected and updated if needed.

**Desktop (please complete the following information):**
 - OS: Raspberry Pi OS
 - Browser [e.g. Chrome, Safari]
 - Version: latest version (Aug 31, 2022)

**Additional context**
Using the docker container. Also tried accessing the IP from the browser, same result

**Comment by manelrodero** [comment]
Hello,

From what I've seen, using 1.1.1.1 may have problems on some routers (eg Orange's LiveBox+).

Also, the page in question gives a 404 Not Found so you will never be able to parse the IP address.
![image](https://user-images.githubusercontent.com/26098260/210349901-021e97cb-8746-4e7e-8539-0dc96b788c95.png)

Instead using cloudflare.com works correctly returning data that could be parsed.
![image](https://user-images.githubusercontent.com/26098260/210349864-537ffb3a-073e-4e56-b184-308c605791f3.png)

**What would be the "solution" to this problem? Make a new commit and release a new image?**

Thanks.

**Comment by iwa** [comment]
I also have Orange as my ISP, and I found a better solution

Problem is, when using `cloudflare.com`, it can sometimes return your ipv6 address (not what we want)

`1.1.1.1` is blocked for whatever reason but it seems `1.0.0.1` isn't (secondary cloudflare dns server)

@timothymiller it would be cool if the script could try to get ipv4 with `1.1.1.1`, and if it doesn't succeed, tries with `1.0.0.1`, and if it still doesnt work, then return an error

@hegocre @manelrodero in the meantime, you can use my image I just built, which uses `1.0.0.1` instead of `1.1.1.1` : https://github.com/iwa/cloudflare-ddns/pkgs/container/cloudflare-ddns

**Comment by timothymiller** [comment]
@iwa I would have appreciated a PR to add support for checking 1.0.0.1 if 1.1.1.1 fails.

 @manelrodero @hegocre I added mainline support for checking 1.0.0.1 if primary IP checks through 1.1.1.1 fails in [this commit](https://github.com/timothymiller/cloudflare-ddns/commit/2ad7e57d652f14ed95f5174c5ca621f3b9030aa6).

**Comment by iwa** [comment]
@timothymiller sry i'm not really good at python, so i just replaced the url and rebuild the image for my usage 😅
thanks for the commit! i'll delete my fork
