### ISSUE TITLE
override not working

### ISSUE THREAD

**Issue by Fleidor** [timothymiller/cloudflare-ddns#2]
for every new IP Adresse it creates a new entry but the old entrys are still there
it is the same for IPv4 and IPv6

**Comment by timothymiller** [comment]
This is inconsistent with the results of my testing. If the A & AAAA records for a specific subdomain have changed, the records will be updated instead of creating new entries. Additionally, if multiple A & AAAA records are detected in the zone (as a result of manually misconfiguring the zone) the entries not matching the current IPv4 and/or IPv6 address will be removed.

**Comment by Fleidor** [comment]
I found the issue.
It was not clear for me, how to write the subdomain, in the config file.
I testet it.
And  now it is working properly.
perhaps you could write an easy example.
like: sub.example.org "sub"


F,

**Comment by timothymiller** [comment]
@Fleidor I pushed a commit which updates the subdomain documentation to read as follows:
`"subdomains": "Array of subdomains you want to update the A & where applicable, AAAA records. IMPORTANT! Only write subdomain name. Do not include the base domain name. (e.g. foo or an empty string to update the base domain)",`
