### ISSUE TITLE
Docker image not running the correct python version

### ISSUE THREAD

**Issue by JHK** [timothymiller/cloudflare-ddns#68]
**Describe the bug**
The docker image won't start and crashes with an error:
```
cloudflare-ddns     | Exception: 🐍 This script requires Python 3.5+
cloudflare-ddns     | Traceback (most recent call last):
cloudflare-ddns     |   File "/cloudflare-ddns.py", line 192, in <module>
```

**To Reproduce**
Take the latest image `timothyjmiller/cloudflare-ddns:latest` and start it.

**Expected behavior**
Should work like before the update.

**Additional context**
I guess it is related to this recent commit: https://github.com/timothymiller/cloudflare-ddns/commit/bf6135739d012b1b020901f7f3259b45c6fa10fb

**Comment by timothymiller** [comment]
@rojosinalma @favonia

**Comment by favonia** [comment]
@timothymiller I don't think @rojosinalma or I introduced bugs. However, you do not have to believe us---you could run
```
docker run timothyjmiller/cloudflare-ddns:latest
```
and see whether the bug is still there. Using Docker images means it does not matter whether who is running it, and @rojosinalma and I only changed two lines of code. I don't feel we (@rojosinalma and I) can provide more explanation than what's already in the pull requests. If it turns out we made a mistake, please feel free to revert at least my change (#67).

@JHK I recommend running `docker pull timothyjmiller/cloudflare-ddns:latest`---what's the digest of the image you using? I suspect that you are suffering from https://github.com/timothymiller/cloudflare-ddns/issues/65 which @rojosinalma fixed. However, again, if a new bug was introduced by me, @timothymiller please just revert the change.

**Comment by JHK** [comment]
It was `sha256:ce0b3c7579f4e2be1b7095abbccce16355d9a1e02d53c272878ef5ffb56777ec` (2 days old). Indeed a pull resolved the issue. Thanks for the pointers!
