### ISSUE TITLE
Specify interface for updating

### ISSUE THREAD

**Issue by andyman1222** [timothymiller/cloudflare-ddns#75]
I am running the container on WSL and I noticed a potential issue. Right now WSL doesn't support IPv6 access, so the container reported "IPv6 not detected". On Windows, WSL creates a virtual ethernet device with a local v4 and v6 address, and I'll assume that local addresses are ignored for cloudflare-ddns.

But, the machine currently running cloudflare-ddns has two network interfaces, ethernet and wifi. I want my domain to point to the ethernet addresses. Since my machine is behind a router, the A record would just point to the public v4 address of the network, but for non-NAT networks and IPv6, it's unclear which address might be used for the records, or perhaps a record might be made for each valid IP address found. Providing an option to specify interfaces under each zone in config.json could fix this issue if it would ever come up.

**Comment by timothymiller** [comment]
I'll keep this one open if someone wants to pick it up.

When running inside a Docker context, the Python code doesn't have low level access to your device's network interfaces, so that will make querying granularly difficult.

That being said, your public IPv4 & IPv6 should be the same regardless of interface type.
